### ISSUE TITLE
peer-to-peer code reviews Tracy-Choice-Eva-Recillah

### ISSUE THREAD

**Issue by Rn486** [techEmprez/My_Portfolio#11]
Good work on this project, you have made the template appear us much as possible as the template.
The template works fine as stipulated in the instructions.
No linter errors.
Good job. Keep it up.

**Comment by elfin-git** [comment]
**Acknowledgements**
- The project is very beautiful and well done
- All the javascript functions works seamlessly

**Suggested changes**
-The contact section has a slightly darker background from the section right on top, see on the figma design.

**Comment by techEmprez** [comment]
Thanks for your feedback
